class TestGameEnv:
    def test_reset_returns_valid_state(self): ...
    def test_step_returns_correct_tuple(self): ...
    def test_agent_clipped_to_boundaries(self): ...
    def test_collision_detected(self): ...
    def test_miss_gives_positive_reward(self): ...